name: Deploy to GitHub Pages

# Este workflow será executado sempre que houver um push para o branch 'main'
on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Baixar o repositório
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Configurar o Node.js na versão 20 para rodar o projeto React
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Instalar as dependências do projeto
      - name: Install dependencies
        run: npm install

      # Construir o projeto React
      - name: Build the project
        run: npm run build

      # Fazer o deploy da pasta 'build' para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
